export const ArchipelagoLocation = {
    HP_BAR_UNLOCK: 1,
    VILLAGE_SHOP_TOP_LOLLIPOP: 100,
    VILLAGE_SHOP_CENTRE_LOLLIPOP: 101,
    VILLAGE_SHOP_BOTTOM_LOLLIPOP: 102,
    VILLAGE_SHOP_CHOCOLATE_BAR: 103,
    VILLAGE_SHOP_TIME_RING: 104,
    VILLAGE_SHOP_CANDY_MERCHANTS_HAT: 105,
    VILLAGE_SHOP_LEATHER_GLOVES: 106,
    VILLAGE_SHOP_LEATHER_BOOTS: 107,
    VILLAGE_HOUSE_1_LOLLIPOP_ON_BOOKSHELF: 200,
    VILLAGE_HOUSE_1_LOLLIPOP_IN_BOOKSHELF: 201,
    VILLAGE_HOUSE_1_LOLLIPOP_UNDER_RUG: 202,
    CELLAR_QUEST: 300,
    POGO_STICK: 500,
    DESERT_QUEST: 1100,
    DESERT_BIRD_FEATHER: 1101,
    BRIDGE_QUEST: 1200,
    THE_TROLLS_BLUDGEON_ACQUIRED: 1201,
    CAVE_EXIT: 1300,
    CAVE_CHOCOLATE_BAR: 1301,
    HEART_PLUG: 1302,
    FOREST_QUEST: 1400,
    CASTLE_ENTRANCE_QUEST: 1500,
    THE_GIANT_NOUGAT_MONSTER_QUEST: 1600,
    SORCERESS_HUT_LOLLIPOP: 1800,
    SORCERESS_HUT_BEGINNER_GRIMOIRE: 1801,
    SORCERESS_HUT_ADVANCED_GRIMOIRE: 1802,
    SORCERESS_HUT_CAULDRON: 1803,
    SORCERESS_HUT_HAT: 1804,
    OCTOPUS_KING_QUEST: 1900,
    MONKEY_WIZARD_QUEST: 2000,
} satisfies Record<string, number>

export const ArchipelagoLocationRegion = {
    VILLAGE_SHOP: ArchipelagoLocation.VILLAGE_SHOP_TOP_LOLLIPOP,
    MOUNTAINS: 500
} satisfies Record<string, number>

export const ArchipelagoItem = {
    CANDY: 0,
    LOLLIPOP: 1,
    CHOCOLATE_BAR: 2,
    HP_BAR: 3,
    TIME_RING: 4,
    CANDY_MERCHANTS_HAT: 5,
    LEATHER_GLOVES: 6,
    LEATHER_BOOTS: 7,
    PROGRESSIVE_WORLD_MAP: 8,
    TROLLS_BLUDGEON: 9,
    DESERT_BIRD_FEATHER: 10,
    BEGINNER_GRIMOIRE: 11,
    ADVANCED_GRIMOIRE: 12,
    CAULDRON: 13,
    SORCERESS_HAT: 14,
    OCTOPUS_KING_CROWN: 15,
    MONKEY_WIZARD_STAFF: 16,
    HEART_PLUG: 17,
    POGO_STICK: 18
} satisfies Record<string, number>

export const ArchipelagoItemBaseId = 7665000