name: Deploy to Pages Branch

on:
  push:
    branches: ["archipelago"]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages-branch"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout Pages Branch
        uses: actions/checkout@v4
        with:
          ref: "pages"
          path: "pages"
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run update-build-tree $GITHUB_WORKSPACE/pages
      - name: Commit
        working-directory: ${{ github.workspace }}/pages
        run: |
          git config --global user.email "vicr12345@gmail.com"
          git config --global user.name "Victor Tran"
          git add .
          git commit -m "Continuous Deployment"
      - name: Push
        working-directory: ${{ github.workspace }}/pages
        run: |
          git push